// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrsqjsgzhiqhzsohffoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyc3Fqc2d6aGlxaHpzb2hmZm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzgxOTMsImV4cCI6MjA2Mzc1NDE5M30.q_Ut5fOCoy4-nZBzQZ4xdEKSN0o-E3X6vsnx_96RFtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);